<?php


namespace UramnOIL\VirtualChestForm\Inventory;


use pocketmine\Player;
use uramnoil\virtualinventory\inventory\VirtualDoubleChestInventory;

class TrashBoxInventory extends VirtualDoubleChestInventory {
	public function onOpen(Player $who) : void {
		if(count($this->getViewers()) >= 1) {
			return;
		}
		parent::onOpen($who); // TODO: Change the autogenerated stub
	}

	public function close(Player $who) : void {
		parent::close($who); // TODO: Change the autogenerated stub
		$this->setContents([]);
	}
}